# Chargement des packages nécessaires au projet
library(dplyr)
library(caret)
library(glmnet)
library(randomForest)
library(class)
library(tidyr)
library(pROC)
library(cluster)
library(mclust)
library(clValid)
library(parallel)
library(ggplot2)
